### PR TITLE
Make it easier to do simple Rupert test.

### PR DESCRIPTION
**Pull request by nanjizal**
Hi currently working on Haxe port, debugging Rupert and being able to swap to the simpler test shape is useful so I can compare with Delaunay test.

### CODE REVIEW

**Comment by nanjizal** [comment]
@mkacz91 not having much success with getting the Rupert test working.
https://github.com/nanjizal/triangulations/blob/master/triangulations/Rupert.hx
If you have time to take a look over the project and advise that would be useful, from the demo you should see it seems to work with most tests in webgl, I will look to implement a Kha version to prove c++ output once it at least works on haxe js.  But knowing how to debug the Rupert code is tricky, especially confused by the line var affectedEdges = 0; when this is an array? Perhaps problem in the split code.

**Comment by nanjizal** [comment]
Azarfe7 spotted some errors in Delaunay, it now seems to work better, but Ruppert is still broken.

**Comment by mkacz91** [comment]
Hey @nanjizal. It would be better to use gitter for this conversation: https://gitter.im/mkacz91/Triangulations

**Comment by nanjizal** [comment]
I now have Ruppert working fine.
demo in haxe webgl javascript, I left some setup info on gitter.
https://rawgit.com/nanjizal/triangulationsWebGLtest/master/index.html

**Comment by mkacz91** [comment]
This pull request does not contribute to this project's aim. I assume that it was just to make contact. since we now have a gitter room associated with this repository, I'm closing this.

**Comment by nanjizal** [comment]
Well it's easier to swap shapes so the only advantage might be for any other users that want to port the code since it's easier to swap to the simpler shape.

**Pull request closed without merging**
